In [4]:
import pandas as pd

In [5]:
data = pd.read_csv(r"C:\Users\Dell\Desktop\Geopulse\gps_data.csv")

In [6]:
data.head()

,lat,lon,timestamp,activity,device_id,persona
0,21.139383,79.063806,8/10/2026 7:24,Home,16bec620-da6a-4450-8aa9-2e45d9a76491,Commuter
1,21.139444,79.063884,8/10/2026 7:27,Home,16bec620-da6a-4450-8aa9-2e45d9a76491,Commuter
2,21.139413,79.063825,8/10/2026 7:30,Home,16bec620-da6a-4450-8aa9-2e45d9a76491,Commuter
3,21.139518,79.064215,8/10/2026 7:33,Home,16bec620-da6a-4450-8aa9-2e45d9a76491,Commuter
4,21.139471,79.064200,8/10/2026 7:36,Home,16bec620-da6a-4450-8aa9-2e45d9a76491,Commuter

In [7]:
data.columns

Index(['lat', 'lon', 'timestamp', 'activity', 'device_id', 'persona'], dtype='object')

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120509 entries, 0 to 120508
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   lat        120509 non-null  float64
 1   lon        120509 non-null  float64
 2   timestamp  120509 non-null  object
 3   activity   120509 non-null  object
 4   device_id  120509 non-null  object
 5   persona    120509 non-null  object
dtypes: float64(2), object(4)
memory usage: 5.5+ MB

In [9]:
data.describe()

                 lat            lon
count  120509.000000  120509.000000
mean       21.132007      79.065467
std         0.039522       0.027590
min        21.039482      79.009419
25%        21.120053      79.050203
50%        21.139542      79.064224
75%        21.160051      79.079417
max        21.169262      79.105912

In [14]:
data.describe(include="all")

,lat,lon,timestamp,activity,device_id,persona
count,120509.000000,120509.000000,120509,120509,120509,120509
unique,NaN,NaN,1204,9,500,3
top,NaN,NaN,8/10/2026 12:40,Home,c3a2bfbc-68e6-4c7d-8b86-59ad87bfd00a,Commuter
freq,NaN,NaN,172,50323,392,66804
mean,21.132007,79.065467,NaN,NaN,NaN,NaN
std,0.039522,0.027590,NaN,NaN,NaN,NaN
min,21.039482,79.009419,NaN,NaN,NaN,NaN
25%,21.120053,79.050203,NaN,NaN,NaN,NaN
50%,21.139542,79.064224,NaN,NaN,NaN,NaN
75%,21.160051,79.079417,NaN,NaN,NaN,NaN
max,21.169262,79.105912,NaN,NaN,NaN,NaN

In [12]:
data.tail()

,lat,lon,timestamp,activity,device_id,persona
120504,21.168905,79.105254,8/10/2026 13:27,Home,7467d70d-8268-42d6-ae34-892326e336db,Resident
120505,21.168680,79.105433,8/10/2026 13:30,Home,7467d70d-8268-42d6-ae34-892326e336db,Resident
120506,21.168738,79.105176,8/10/2026 13:33,Home,7467d70d-8268-42d6-ae34-892326e336db,Resident
120507,21.168766,79.105199,8/10/2026 13:36,Home,7467d70d-8268-42d6-ae34-892326e336db,Resident
120508,21.168649,79.105360,8/10/2026 13:39,Home,7467d70d-8268-42d6-ae34-892326e336db,Resident

In [13]:
data.dtypes

lat          float64
lon          float64
timestamp     object
activity      object
device_id     object
persona       object
dtype: object

In [17]:
missing_values = data.isnull().sum()
missing_values

lat          0
lon          0
timestamp    0
activity     0
device_id    0
persona      0
dtype: int64

In [19]:
missing_percentage = (
    data.isnull().sum() / len(data) * 100
).round(2)

missing_percentage

lat          0.0
lon          0.0
timestamp    0.0
activity     0.0
device_id    0.0
persona      0.0
dtype: float64

In [20]:
duplicate_count = data.duplicated().sum()

print("Duplicate records:", duplicate_count)

Duplicate records: 0

In [21]:
data["timestamp"] = pd.to_datetime(
    data["timestamp"],
    errors="coerce"
)

In [22]:
data.dtypes

lat                 float64
lon                 float64
timestamp    datetime64[ns]
activity             object
device_id            object
persona              object
dtype: object

In [24]:
invalid_timestamp = data["timestamp"].isna().sum()
print(
    "Invalid timestamps:",
    invalid_timestamp
)

Invalid timestamps: 0

In [25]:
data["lat"] = pd.to_numeric(
    data["lat"],
    errors="coerce"
)

data["lon"] = pd.to_numeric(
    data["lon"],
    errors="coerce"
)

In [26]:
data[["lat", "lon"]].dtypes

lat    float64
lon    float64
dtype: object