In [1]:
# import library
import pandas as pd
import numpy as np
import os

In [2]:
# load data
data = pd.read_csv(r"C:\Users\Dell\Desktop\Geopulse\gps_data.csv")

C:\Users\Dell\AppData\Local\Temp\ipykernel_21300\2860580658.py:2: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(r"C:\Users\Dell\Desktop\Geopulse\gps_data.csv")

In [3]:
# view first 5 records
data.head()

,lat,lon,timestamp,activity,device_id,persona
0,21.13938323,79.06380644,8/10/2026 7:24,Home,16bec620-da6a-4450-8aa9-2e45d9a76491,Commuter
1,21.13944362,79.06388352,8/10/2026 7:27,Home,16bec620-da6a-4450-8aa9-2e45d9a76491,Commuter
2,21.13941327,79.06382484,8/10/2026 7:30,Home,16bec620-da6a-4450-8aa9-2e45d9a76491,Commuter
3,21.13951761,79.06421495,8/10/2026 7:33,Home,16bec620-da6a-4450-8aa9-2e45d9a76491,Commuter
4,21.13947058,79.06419953,8/10/2026 7:36,Home,16bec620-da6a-4450-8aa9-2e45d9a76491,Commuter

In [4]:
# column names
data.columns

Index(['lat', 'lon', 'timestamp', 'activity', 'device_id', 'persona'], dtype='object')

In [5]:
# dataset information
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243051 entries, 0 to 243050
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   lat        243051 non-null  object
 1   lon        243049 non-null  object
 2   timestamp  243049 non-null  object
 3   activity   243049 non-null  object
 4   device_id  243049 non-null  object
 5   persona    243049 non-null  object
dtypes: object(6)
memory usage: 11.1+ MB

In [6]:
# statistical summary
data.describe()

,lat,lon,timestamp,activity,device_id,persona
count,243051,243049,243049,243049,243049,243049
unique,195899,217393,1207,10,1001,4
top,21.16870384,79.05002072,8/10/2026 7:59,Home,c3a2bfbc-68e6-4c7d-8b86-59ad87bfd00a,Commuter
freq,8,5,348,100916,392,140235

In [7]:
data.describe(include="all")

,lat,lon,timestamp,activity,device_id,persona
count,243051,243049,243049,243049,243049,243049
unique,195899,217393,1207,10,1001,4
top,21.16870384,79.05002072,8/10/2026 7:59,Home,c3a2bfbc-68e6-4c7d-8b86-59ad87bfd00a,Commuter
freq,8,5,348,100916,392,140235

In [8]:
# view last records
data.tail()

,lat,lon,timestamp,activity,device_id,persona
243046,21.16857045,79.105571,8/10/2026 17:30,Home,b0729526-9ee1-4dd0-a983-32e015329898,Shopper
243047,21.168764,79.105006,8/10/2026 17:33,Home,b0729526-9ee1-4dd0-a983-32e015329898,Shopper
243048,21.16875659,79.105273,8/10/2026 17:36,Home,b0729526-9ee1-4dd0-a983-32e015329898,Shopper
243049,21.16839902,79.105431,8/10/2026 17:39,Home,b0729526-9ee1-4dd0-a983-32e015329898,Shopper
243050,>>>>>>> b2d97e35a308cf1a90a6018ec20dc9fe6f8c6788,NaN,NaN,NaN,NaN,NaN

In [9]:
# checking data types
data.dtypes

lat          object
lon          object
timestamp    object
activity     object
device_id    object
persona      object
dtype: object

In [10]:
# missing values
missing_values = data.isnull().sum()
missing_values

lat          0
lon          2
timestamp    2
activity     2
device_id    2
persona      2
dtype: int64

In [11]:
# Missing value percentage
missing_percentage = (
    data.isnull().sum() / len(data) * 100
).round(2)

missing_percentage

lat          0.0
lon          0.0
timestamp    0.0
activity     0.0
device_id    0.0
persona      0.0
dtype: float64

In [12]:
# duplicate records 
duplicate_count = data.duplicated().sum()

print("Duplicate records:", duplicate_count)

Duplicate records: 0

In [13]:
# convert timestamp
data["timestamp"] = pd.to_datetime(
    data["timestamp"],
    errors="coerce"
)

In [14]:
# checking 
data.dtypes

lat                  object
lon                  object
timestamp    datetime64[ns]
activity             object
device_id            object
persona              object
dtype: object

In [15]:
# check invalid timestamps 
invalid_timestamp = data["timestamp"].isna().sum()
print(
    "Invalid timestamps:",
    invalid_timestamp
)

Invalid timestamps: 3

In [16]:
# check GPS data types
data["lat"] = pd.to_numeric(
    data["lat"],
    errors="coerce"
)

data["lon"] = pd.to_numeric(
    data["lon"],
    errors="coerce"
)

In [17]:
data[["lat", "lon"]].dtypes

lat    float64
lon    float64
dtype: object

In [ ]:
# checking latitude
invalid_lat = (
    (data["lat"] < -90) |
    (data["lat"] > 90)
)

print(
    "Invalid latitude records:",
    invalid_lat.sum()
)

Invalid latitude records: 0

In [20]:
# checking longitude
invalid_lon = (
    (data["lon"] < -180) |
    (data["lon"] > 180)
)

print(
    "Invalid longitude records:",
    invalid_lon.sum()
)

Invalid longitude records: 0

In [21]:
# Checking simulated study area
MIN_LAT = 20.95
MAX_LAT = 21.25

MIN_LON = 78.90
MAX_LON = 79.20

In [22]:
outside_area = (
    (data["lat"] < MIN_LAT) |
    (data["lat"] > MAX_LAT) |
    (data["lon"] < MIN_LON) |
    (data["lon"] > MAX_LON)
)

print(
    "Records outside study area:",
    outside_area.sum()
)

Records outside study area: 0

In [23]:
# checking devices
unique_devices = data["device_id"].nunique()

print(
    "Unique devices:",
    unique_devices
)

Unique devices: 1001

In [24]:
data["device_id"].value_counts().describe()

count    1001.000000
mean      242.806194
std        84.682728
min         1.000000
25%       168.000000
50%       207.000000
75%       334.000000
max       392.000000
Name: count, dtype: float64

In [25]:
# Checking personas
data["persona"].value_counts()

persona
Commuter    140235
Resident     63538
Shopper      39275
persona          1
Name: count, dtype: int64

In [26]:
# percentage
(
    data["persona"]
    .value_counts(normalize=True)
    * 100
).round(2)

persona
Commuter    57.70
Resident    26.14
Shopper     16.16
persona      0.00
Name: proportion, dtype: float64

In [27]:
# checking activities
data["activity"].value_counts()

activity
Home               100916
Work                49308
Commute to Work     24780
Commute to Home     24780
Return Home         15600
Local Activity       7904
Local Movement       7880
Travel to Store      7720
Shopping             4160
activity                1
Name: count, dtype: int64

In [28]:
# Clean text fields
data["persona"] = (
    data["persona"]
    .astype(str)
    .str.strip()
)

data["activity"] = (
    data["activity"]
    .astype(str)
    .str.strip()
)

In [29]:
# Sort the GPS records
data = data.sort_values(
    by=["device_id", "timestamp"]
).reset_index(drop=True)

In [30]:
# Now FEATURE ENGINEERING
# This isn't strictly "cleaning", but it's an important next stage of your data preparation.
# Create date

data["date"] = data["timestamp"].dt.date

In [31]:
# Create hour
data["hour"] = data["timestamp"].dt.hour

In [32]:
# Create day of week

data["day_of_week"] = (
    data["timestamp"]
    .dt.day_name()
)

In [33]:
# Create time period

def get_time_period(hour):

    if 7 <= hour < 10:
        return "Morning"

    elif 10 <= hour < 16:
        return "Afternoon"

    elif 16 <= hour < 20:
        return "Evening"

    else:
        return "Night"


data["time_period"] = (
    data["hour"]
    .apply(get_time_period)
)

In [34]:
# checking it

data["time_period"].value_counts()

time_period
Afternoon    114945
Morning       50445
Evening       40832
Night         36829
Name: count, dtype: int64

In [35]:
# check the final structure

data.shape

(243051, 10)

In [36]:
data.columns.tolist()

['lat',
 'lon',
 'timestamp',
 'activity',
 'device_id',
 'persona',
 'date',
 'hour',
 'day_of_week',
 'time_period']

In [37]:
data.head()

,lat,lon,timestamp,activity,device_id,persona,date,hour,day_of_week,time_period
0,21.160203,79.073202,2026-08-10 07:51:00,Home,00319880-b2a0-456e-9fe3-3f1d70d8f1fe,Commuter,2026-08-10,7.0,Monday,Morning
1,21.159938,79.073187,2026-08-10 07:54:00,Home,00319880-b2a0-456e-9fe3-3f1d70d8f1fe,Commuter,2026-08-10,7.0,Monday,Morning
2,21.160004,79.073091,2026-08-10 07:57:00,Home,00319880-b2a0-456e-9fe3-3f1d70d8f1fe,Commuter,2026-08-10,7.0,Monday,Morning
3,21.159969,79.072992,2026-08-10 08:00:00,Home,00319880-b2a0-456e-9fe3-3f1d70d8f1fe,Commuter,2026-08-10,8.0,Monday,Morning
4,21.160182,79.072877,2026-08-10 08:03:00,Home,00319880-b2a0-456e-9fe3-3f1d70d8f1fe,Commuter,2026-08-10,8.0,Monday,Morning

In [38]:
# Final quality check

print("Rows:", len(data))
print("Columns:", len(data.columns))

print("\nMissing values:")
print(data.isnull().sum())

print("\nDuplicate rows:")
print(data.duplicated().sum())

print("\nData types:")
print(data.dtypes)

Rows: 243051
Columns: 10

Missing values:
lat            3
lon            3
timestamp      3
activity       0
device_id      2
persona        0
date           3
hour           3
day_of_week    3
time_period    0
dtype: int64

Duplicate rows:
1

Data types:
lat                   float64
lon                   float64
timestamp      datetime64[ns]
activity               object
device_id              object
persona                object
date                   object
hour                  float64
day_of_week            object
time_period            object
dtype: object

In [39]:
# Save cleaned CSV
os.makedirs(
    "data/processed",
    exist_ok=True
)

In [40]:
output_file = "data/processed/gps_data_clean.csv"

data.to_csv(
    output_file,
    index=False
)

print(
    "Clean CSV saved successfully!"
)

print(
    output_file
)

Clean CSV saved successfully!
data/processed/gps_data_clean.csv